
-- =============================================================================
-- Component 15: TDSTATS Native Recommendations (Pure SQL)
-- =============================================================================
-- Description : Extracts missing statistics recommendations directly from 
--               Teradata's automated AutoStats engine (TDSTATS.StatsUsageReport).
--               Dynamically fetches the latest AnalysisId generated by the SP.
--               Cross-references native recommendations with physical table 
--               size to avoid collecting on empty tables/headers (> 10MB).
-- 
-- Version     : 1.1.0
-- Date        : 2026-05-15
-- Modificado  : 2026-05-15 - Adaptación a SQL puro (Two-Step execution)
-- Author      : Ricardo Enciso
-- Environment : Teradata 20
-- =============================================================================

WITH Ultimo_Analisis AS (
    -- Captura dinámicamente la última ejecución del SP que acabas de lanzar
    SELECT MAX(AnalysisId) AS Max_AnalysisId
    FROM TDSTATS.AnalyzeStatsUsage
),
Tablas_Fisicas AS (
    -- Blindaje físico: Ignorar tablas vacías y Table Headers
    SELECT DatabaseName, TableName, SUM(CurrentPerm) AS CurrentPerm
    FROM DBC.TableSizeV
    GROUP BY 1, 2
    HAVING SUM(CurrentPerm) > 10485760 -- > 10 MB
)
SELECT 
    r.DatabaseName,
    r.TableName,
    r.FieldNames AS Columnas_Recomendadas,
    r.EventType,
    CAST(tf.CurrentPerm / (1024.0**3) AS DECIMAL(18,2)) AS Size_GB,
    -- Generación del comando ejecutable
    'COLLECT STATISTICS COLUMN (' || TRIM(r.FieldNames) || ') ON ' || TRIM(r.DatabaseName) || '.' || TRIM(r.TableName) || ';' AS Action_SQL
FROM TDSTATS.StatsUsageReport r
INNER JOIN Ultimo_Analisis ua
    ON r.AnalysisId = ua.Max_AnalysisId
INNER JOIN DBC.TablesV t
    ON r.DatabaseName = t.DatabaseName
    AND r.TableName = t.TableName
INNER JOIN Tablas_Fisicas tf
    ON r.DatabaseName = tf.DatabaseName
    AND r.TableName = tf.TableName
WHERE t.TableKind IN ('T', 'O', 'Q')
  AND r.EventType IN ('M', 'S') -- 'M' = Missing, 'S' = Stale
  AND r.DatabaseName NOT IN (
        'DBC','DBCMNGR','SYSLIB','TDQCD','TDSTATS','TDMAPS','TDBCMGMT',
        'TD_SERVER_DB','VAL','SYSTEMFE','SYSSPATIAL','VIEWPOINT','TDWM',
        'LOCKLOGLSHREDDER','SQLJ','SYSBAR','SYSADMIN','SYS_CALENDAR',
        'TD_ANALYTICS_DB','PDCRTPCD','PDCRDATA','PDCRSTG','SYSDBA', 'CONSOLE'
  )
ORDER BY Size_GB DESC;