-- =============================================================================
-- Component   : Sqltextinfo014
-- =============================================================================
-- Description : Monthly report query for Teradata DBA Services Framework
--
-- Version     : 1.0.0
-- Date        : 2026-05-05
-- Author      : Ricardo Enciso
-- Environment : Teradata 20
-- =============================================================================
 EXEC pdcrinfo.CapSystem_DiskIO_Rpt (dAtE'2026-04-01' , dAtE'2026-04-30') ;