-- =============================================================================
-- Component   : Sqltextinfo018
-- =============================================================================
-- Description : Monthly report query for Teradata DBA Services Framework
--
-- Version     : 1.0.0
-- Date        : 2026-05-05
-- Author      : Ricardo Enciso
-- Environment : Teradata 20
-- =============================================================================
 EXEC pdcrinfo.CapSystem_CPU_Rpt (dAtE'2025-05-05' , dAtE'2026-05-05') ;